### ISSUE TITLE
Help i have an issue

### ISSUE THREAD

**Issue by deffan10** [ryanaidilp/sistem_absensi_pegawai#26]
I wanna try this app for my univ project. 
But i got the problem when create voyager admin and db:seed. 
i think u must upload some example of the users.csv and departments.csv

Nice app btw
![image](https://user-images.githubusercontent.com/49578199/108820855-5d6d2680-75ef-11eb-9a43-66432ea13ce0.png)
![image](https://user-images.githubusercontent.com/49578199/108820896-678f2500-75ef-11eb-9055-21c00250711c.png)

**Comment by ryanaidilp** [comment]
@deffan10 I have uploaded the csv files, you can check it in the repository now
