### ISSUE TITLE
Permisi bang , Mau tanya , saya gunawan

### ISSUE THREAD

**Issue by gop4sch4** [ryanaidilp/sistem_absensi_pegawai#31]
http://localhost:8000/admin
error
Route [voyager.departments.index] not defined. (View: D:\xampp\htdocs\sistem_absensi_pegawai\vendor\tcg\voyager\resources\views\dimmers.blade.php)
![screenshotAtUploadCS_1614765009977](https://user-images.githubusercontent.com/35401990/109787374-bddc1380-7c40-11eb-93c2-15eca056c7dc.png)
![screenshotAtUploadCS_1614765009976](https://user-images.githubusercontent.com/35401990/109787382-bfa5d700-7c40-11eb-892b-a4590dc1c793.png)

Minta solusinya bang , terima kasih

**Comment by ryanaidilp** [comment]
Buka file voyager.php di folder config terus hapus/comment line ini
![image](https://user-images.githubusercontent.com/43450710/109978179-91a3be00-7d38-11eb-8f45-5e978f3c52d3.png)
