### ISSUE TITLE
sample database , please 

### ISSUE THREAD

**Issue by gop4sch4** [ryanaidilp/sistem_absensi_pegawai#32]
latest ver sample database please ,dan env  nya please

**Comment by ryanaidilp** [comment]
nampaknya contoh struktur databasenya sudah bisa dilihat dari hasil migrasi nya, saya juga udah upload contoh data csv untuk user dan departemen. Kalau .env yang perlu ditambahkan hanya variabel yang sudah saya tuliskan pada readme, sisanya hanya variabel konfigurasi bawaan Laravel.
