### ISSUE TITLE
ini kenapa yah bang

### ISSUE THREAD

**Issue by pras168** [ryanaidilp/sistem_absensi_pegawai#42]
Invalid argument supplied for foreach() (View: C:\xampp\htdocs\sistem_absensi_pegawai-master\vendor\tcg\voyager\resources\views\dimmers.blade.php)

**Comment by ryanaidilp** [comment]
maaf mas baru sempat bales, coba cek ke sini #31 . kayaknya case yang dialami hampir serupa. Kalau masih error, tolong tambahin info gimana buat reproduce errornya biar saya bisa coba lacak errornya
