### ISSUE TITLE
General error: 1364 Field 'gender_id' doesn't have a default value

### ISSUE THREAD

**Issue by agasmaulana** [ryanaidilp/sistem_absensi_pegawai#48]
Ini kenapa setelah saya jalankan perintah php artisan voyager:admin email_anda@mail.com --create kok timbul error seperti digambar ya?
![image](https://user-images.githubusercontent.com/101586560/175495686-6a27fc42-0d96-4c1b-9e2f-b7063a0e047c.png)

**Comment by rizkifauzanakbar** [comment]
mas @ryanaidilp tolong info untuk solved error di atas mas, terimakasih

**Comment by ryanaidilp** [comment]
tambahin default value ke kolom gender_id di file migration nya atau buat kolom nya jadi nullable. Dari exception nya udah jelas kan ya, pastiin urutannya juga sesuai (tabel gender harus udah migrate sebelum nambahin gender id ke tabel user).

**Comment by rizkifauzanakbar** [comment]
Sipppp makasih mas
